# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
