# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_profile_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adsress',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=10),
        ),
    ]
