# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20190402_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('d', 'Delhi'), ('k', 'Kolkata'), ('c', 'Chennai'), ('p', 'Punjab')], default='', max_length=10),
        ),
    ]
