# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_auto_20190402_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=''),
        ),
    ]
