# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_auto_20190402_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
    ]
