# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_auto_20190402_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=9798779686),
        ),
        migrations.AddField(
            model_name='profile',
            name='postalcode',
            field=models.IntegerField(default=123456),
        ),
    ]
