# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0013_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
